#!/bin/sh

set -e

INSTALER_EXE=b21_S4_L6r_x64

docker build -t windows-installer -f Dockerfile.windows .
CONTAINER="$(docker run -d windows-installer)"
mkdir -p dist
docker cp "${CONTAINER}":/installer/Output/b21_S4_L6r_x64.exe dist/
docker rm "${CONTAINER}" 2>/dev/null || true
