#!/bin/sh

set -e

INSTALER_EXE=G7-windows-i386.exe

docker build -t windows-installer -f Dockerfile.windows .
CONTAINER="$(docker run -d windows-installer)"
mkdir -p dist
docker cp "${CONTAINER}":/installer/Output/$INSTALER_EXE dist/
docker rm "${CONTAINER}" 2>/dev/null || true
